trigger:
  branches:
    include:
      - master
  paths:
    include:
      - examples/next
pr: none

variables:
  PoolDev: crazyjane-linux-dev
  PoolBeta: crazyjane-linux-beta
  AcrHost: acreuwglobal.azurecr.io

name: $(Build.SourceBranch).$(Date:yyyyMMdd)$(Rev:.r)

stages:
  - stage: 'BuildApp'
    pool:
      name: $(PoolDev)
    variables:
      - group: 'junojs-examples-next'
    jobs:
      - job: build_app
        workspace:
          clean: all
        steps:
          - checkout: self
            persistCredentials: true
          - template: ./steps/install.yaml
            parameters:
              Filter: $(ProjectName)
          - template: ./steps/build.yaml
            parameters:
              Filter: $(ProjectName)
          - template: ./steps/docker.yaml
            parameters:
              ContainerRepository: $(ContainerRepository)
              ContainerRegistry: $(ContainerRegistry)
              Dockerfile: './Dockerfile'
              ProjectPath: $(ProjectPath)
              ProjectName: $(ProjectName)

  - stage: 'DeployDev'
    condition: succeeded('BuildApp')
    pool:
      name: $(PoolDev)
    variables:
      - group: 'junojs-examples-next - dev'
    jobs:
      - template: ./stages/deploy-app-k8s.yaml
        parameters:
          EnvName: 'dev'
          Pool: $(PoolDev)
          DeploymentAppName: $(DeploymentAppName)
          Repository: $(ContainerRepository)
          KubernetesServiceConnection: $(AKSServiceConnectionDev)
          KubernetesNamespace: $(AKSNamespace)
          KubernetesDeploymentConfigurationPath: './examples/next/k8sdeployment.yaml'

  - stage: 'DeployBeta'
    condition: succeeded('BuildApp')
    pool:
      name: $(PoolBeta)
    variables:
      - group: 'junojs-examples-next - beta'
    jobs:
      - template: ./stages/deploy-app-k8s.yaml
        parameters:
          EnvName: 'beta'
          Pool: $(PoolBeta)
          DeploymentAppName: $(DeploymentAppName)
          Repository: $(ContainerRepository)
          KubernetesServiceConnection: $(AKSServiceConnectionBeta)
          KubernetesNamespace: $(AKSNamespace)
          KubernetesDeploymentConfigurationPath: './examples/next/k8sdeployment.yaml'
