parameters:
  - name: EnvName
    type: string
  - name: Pool
    type: string
  - name: DeploymentAppName
    type: string
  - name: Repository
    type: string
  - name: KubernetesServiceConnection
    type: string
  - name: KubernetesNamespace
    type: string
  - name: KubernetesDeploymentConfigurationPath
    type: string

jobs:
  - job: deploy_${{ parameters.EnvName }}
    displayName: 'Deploy ${{ parameters.EnvName }}'

    steps:
      - task: replacetokens@3
        displayName: 'Replace tokens in k8s deployment'
        inputs:
          targetFiles: '${{ parameters.KubernetesDeploymentConfigurationPath }}'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: false

      - task: Kubernetes@1
        displayName: Apply deployment in aks
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: '${{ parameters.KubernetesServiceConnection }}'
          namespace: '${{ parameters.KubernetesNamespace }}'
          command: 'apply'
          useConfigurationFile: true
          configuration: '${{ parameters.KubernetesDeploymentConfigurationPath }}'
