trigger:
  - master
pr: none
pool:
  demands:
    - npm

variables:
  - name: turbo_cache_path
    value: $(Pipeline.Workspace)/.turbo
  - group: githubcommentingboprakvp

name: $(Build.SourceBranchName).$(Date:yyyyMMdd)$(Rev:.r)
jobs:
  - job: release
    displayName: "Publish release"
    steps:
      - checkout: self
        persistCredentials: true

      - template: /.azure-templates/steps/cache-turbo.yml
        parameters:
          turbo_cache_path: $(turbo_cache_path)

      - template: /.azure-templates/steps/checkout-branch.yml
        parameters:
          branch: master
      - template: /.azure-templates/steps/install.yml
      - script: pnpm turbo build --filter='./packages/*' --cache-dir=$(turbo_cache_path)
        displayName: "build"
      - template: /.azure-templates/steps/release.yml
