trigger: none
pr: none
pool:
  demands:
    - npm

variables:
  - name: turbo_cache_path
    value: $(Pipeline.Workspace)/.turbo
  - group: githubcommentingboprakvp

name: $(Build.SourceBranchName).$(Date:yyyyMMdd)$(Rev:.r)
jobs:
  - job: release
    displayName: "Publish prerelease."
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - template: /.azure-templates/steps/cache-turbo.yml
        parameters:
          turbo_cache_path: $(turbo_cache_path)

      - template: /.azure-templates/steps/set-current-branch.yml
        parameters:
          sourceBranch: $(Build.SourceBranch)
      - template: /.azure-templates/steps/checkout-branch.yml
        parameters:
          branch: $(setCurrentBranch.BRANCH_NAME)

      - task: CmdLine@2
        displayName: "Checkout prerelease current branch"
        inputs:
          script: |
            git checkout -b prerelease/$(Build.BuildNumber)

      - task: CmdLine@2
        displayName: "Push current branch to prerelease branch"
        inputs:
          script: |
            git push --set-upstream origin prerelease/$(Build.BuildNumber)

      - template: /.azure-templates/steps/install.yml

      - script: pnpm turbo build --filter='./packages/*' --cache-dir=$(turbo_cache_path)
        displayName: "build"

      - template: /.azure-templates/steps/prerelease.yml
        parameters:
          distTag: "echo $(setCurrentBranch.BRANCH_NAME) | sed -r 's/[_/.]+/-/g'"
