trigger: none
pr:
  branches:
    include:
      - "*"
resources:
  - repo: self
pool:
  demands:
    - npm

variables:
  turbo_cache_path: $(Pipeline.Workspace)/.turbo

name: $(Build.SourceBranch).$(Date:yyyyMMdd)$(Rev:.r)
jobs:
  - job: local
    displayName: "Pull Request validation"
    steps:
      - checkout: self
        persistCredentials: true
      - template: /.azure-templates/steps/cache-turbo.yml
        parameters:
          turbo_cache_path: $(turbo_cache_path)
      - template: /.azure-templates/steps/reports-mkdir.yml
      - template: /.azure-templates/steps/install.yml
      - script: pnpm turbo build --cache-dir=$(turbo_cache_path)
        displayName: "build"
      - template: /.azure-templates/steps/quality-check.yml
      - template: /.azure-templates/steps/publish-reports.yml
