trigger: none
pr: none
pool:
  demands:
    - npm
    - java

variables:
  turbo_cache_path: $(Pipeline.Workspace)/.turbo

name: $(Build.SourceBranchName).$(Date:yyyyMMdd)$(Rev:.r)
jobs:
  - job: local
    displayName: "Run Sonar analysis"
    steps:
      - checkout: self
        persistCredentials: true

      - template: /.azure-templates/steps/cache-turbo.yml
        parameters:
          turbo_cache_path: $(turbo_cache_path)

      - template: /.azure-templates/steps/install.yml
      - template: /.azure-templates/steps/reports-mkdir.yml
      - template: /.azure-templates/steps/quality-check.yml
      - template: /.azure-templates/steps/eslint-full.yml
      - template: /.azure-templates/steps/sonar-base.yml
        parameters:
          projects:
            - key: root
              path: .
              sonarConfig: "./sonar-project.properties"
              projectVersion: "node -p 'require(`./lerna.json`).version'"
