name: pnpm dependencies audit

on:
  push:
    branches: ["master"]
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * *'
jobs:
  audit:

    runs-on: [self-hosted, Linux, azure, prod, deployment]
    permissions:
      id-token: write
      contents: write
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install

      - name: audit
        uses: GrupaPracuj/GP.MrRobot/pnpm-audit@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          compact: true
